### ISSUE TITLE
top k logic issue

### ISSUE THREAD

**Issue by tedzhao226** [IBM/MAX-Places365-CNN#44]
I think it should be `x.sort(1, True)`,   and the results should be the same with `torch.topk` API.

https://github.com/IBM/MAX-Scene-Classifier/blob/0927fc5788c3bc4ede43edf6bc0e626f40976f9b/core/model.py#L93

Sample codes:

```python
>>> import torch
>>> probs = torch.tensor([[0.0297, 0.3163, 0.4335, 0.2205],
                [0.3554, 0.2583, 0.3467, 0.0396],
                [0.3997, 0.4566, 0.0879, 0.0557]])

>>> probs.sort(1,True)

orch.return_types.sort(
values=tensor([[0.4335, 0.3163, 0.2205, 0.0297],
        [0.3554, 0.3467, 0.2583, 0.0396],
        [0.4566, 0.3997, 0.0879, 0.0557]]),
indices=tensor([[2, 1, 3, 0],
        [0, 2, 1, 3],
        [1, 0, 2, 3]]))

>>> torch.topk(probs, 4)

torch.return_types.topk(
values=tensor([[0.4335, 0.3163, 0.2205, 0.0297],
        [0.3554, 0.3467, 0.2583, 0.0396],
        [0.4566, 0.3997, 0.0879, 0.0557]]),
indices=tensor([[2, 1, 3, 0],
        [0, 2, 1, 3],
        [1, 0, 2, 3]]))
```

**Comment by xuhdev** [comment]
By default, `topk` performs on the last dimension. Since your examples are all 2-dimensional, it makes sense that it corresponds to `sort(1, True)`. Since the line you cited is on a 1-dimensional tensor, `sort(0, True)` would correspond to a `topk` call. Nevertheless, I made a PR to fix this part of the code to use `topk`, which would be less confusing.
